/* DO NOT EDIT THIS FILE - it is machine generated */
#include""
/* Header for class com_wangqi_appbsdiff_AppDiffUtil */

#ifndef _Included_com_wangqi_appbsdiff_AppDiffUtil
#define _Included_com_wangqi_appbsdiff_AppDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangqi_appbsdiff_AppDiffUtil
 * Method:    appDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wangqi_appbsdiff_AppDiffUtil_appDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
